export interface Pessoa {
  id: number,
  nome: string,
  cpf_cnpj: string,
  tipo: string,
  data_nascimento?: string,
  sexo?: string,
  telefone1?: string,
  telefone2?: string,
  telefone3?: string,
  email?: string,
  endereco?: string,
  numero?: string,
  complemento?: string,
  bairro?: string,
  cidade?: string,
  uf?: string,
  cep?: string,
  cliente: number,
  fornecedor: number,
  funcionario: number,
}
